### ISSUE TITLE
submit talk to useR 2021

### ISSUE THREAD

**Issue by maxheld83** [subugoe/muggle#192]
> Between GUI-based reports and scripted data science lies an unproductive valley that combines the worst of both worlds:
> poor scaleability *and* high overhead.
> To avoid getting stuck there, small and medium-sized teams must 1) build strategic data products (not one-off scripts), 2) adopt software development best practices (not hacks) and 3) concentrate on business value (not infrastructure).
> 
> 1) Strategic data products focus on the ETL pipelines, common visualisations and other modules that are central to the mission. These unix-style building blocks can then be recombined into various reports.
> 2) These modules are designed "as-if-for-CRAN" and written as type/length-stable, unit-tested and exported functions. 
> 3) If something is not related to our mission, we rely on industry standards (Docker) and CaaS/DBaaS (Azure, GCP).
> 
> {muggle}'s opininated DevOps provides some technical scaffolding to help with this transition.
> It standardises the compute environment in development, testing and deployment on a multi-stage `Dockerfile` with `ONBUILD` triggers for lightweight target images and leverages public cloud services (RSPM, GitHub Actions, GitHub Packages).
> In contrast to some existing approaches, {muggle} never infers developer intent and has a minimal git footprint.
> 
> Success also requires a cultural shift. Development may still be agile, but it must not build prototype code. Fancy plots and reports are good, but reproducibility is more important.
> 
> We believe this is a necessary change to ensure value generation, and thereby, to ensure the future of democratic, and open-source data science.

**Comment by maxheld83** [comment]
@njahn82 I decided spontaneously to submit muggle to useR (which will be remote again, conveniently).
Since this is largely based on our experiences / practices at SUB, can I list you as a co-author?

**Comment by njahn82** [comment]
Cool, thanks!
